name: scrapy
channels:
  - defaults
dependencies:
  - ca-certificates
  - certifi=2020.12.5
  - libcxx
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.8.8
  - setuptools=52.0.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - requests
    - xmltodict
    - Scrapy==1.8.0
    - Scrapy-UserAgents
    - twisted==20.3.0
    - redis==3.4.1
    - google-cloud-storage==1.26.0
    - jsonschema==3.0.2
    - python-dateutil==2.8.0
    - google-cloud-firestore==1.6.2
    - pandas==1.0.3
