version: "3.9"

services:

  scrapy:
    container_name: scrapy
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file:
      - env-docker-compose.env
    networks:
      - webnet   
  redis:
    image: redis:buster
    container_name: redis
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - webnet
networks:
  webnet:
